# Generated by Django 5.1 on 2026-03-02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=255)),
                ("company", models.CharField(max_length=255)),
                ("location", models.CharField(max_length=255)),
                ("salary", models.CharField(blank=True, max_length=128)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("full-time", "Full time"),
                            ("part-time", "Part time"),
                            ("contract", "Contract"),
                            ("remote", "Remote"),
                            ("hybrid", "Hybrid"),
                        ],
                        default="full-time",
                        max_length=32,
                    ),
                ),
                ("posted_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("description", models.TextField()),
                ("requirements", models.JSONField(blank=True, default=list)),
                ("logo", models.URLField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-posted_at", "-created_at"],
            },
        ),
    ]
